- name: Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  become: yes

- name: jq
  apt:
    name:
    - jq
    state: latest
  become: true

- name: Spotify
  snap:
    name:
      - spotify
  become: true

- name: Flameshot
  apt:
    name:
    - flameshot
    state: latest
  become: true

- name: Flameshot - Create .config folder
  file:
    path: $HOME/.config
    state: directory
    mode: '0755'
