- name: Chrome Install
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  become: yes

- name: jq Install
  apt:
    name:
    - jq
    state: latest
  become: true

- name: Slack Install
  apt:
    deb: https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-desktop-4.23.0-amd64.deb
    state: present
  become: yes

- name: Spotify - Install gpg key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
  become: yes

- name: Spotify - Add APT Repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
  become: true

- name: Flameshot install
  apt:
    name:
    - flameshot
    state: latest
  become: true

- name: Flameshot - Create .config folder
  file:
    path: $HOME/.config
    state: directory
    mode: '0755'

- name: Flameshot Shortcut
  copy:
    src: ../files/khotkeysrc
    dest: $HOME/.config/khotkeysrc
    backup: yes

- name: Ulauncher - Add PPA Repository
  apt_repository:
    repo: ppa:agornostal/ulauncher
    state: present
  become: true

- name: Spotify Install
  apt:
    name:
    - spotify-client
    update_cache: yes
    state: latest
  become: true

- name: Ulauncher Install
  apt:
    name:
    - ulauncher
    state: latest
  become: true
