- name: Install Docker Dependencies
  apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-apt
    state: latest
    cache_valid_time: 3600
    update_cache: yes
  become: yes
  
- name: Install gpg Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker APT Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: Install Docker Engine
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    update_cache: yes
    state: latest
  become: true