- name: Check if Docker is Already Installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Download Docker Install Script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
  when: not docker_installed.stat.exists

- name: Install Docker
  shell: sh /tmp/get-docker.sh
  when: not docker_installed.stat.exists
  become: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
  become: yes

- name: Add Current User to Docker Group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    state: present
    append: yes
  become: yes