# Dependencies
- name: Install PyMySQL (Module Requirements)
  pip:
    name: pymysql
    state: present
  become: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    cache_valid_time: 3600
    update_cache: yes
  become: yes

# - name: Change Root Password
#   mysql_user:
#     name: root
#     password: "{{ mysql_root_password }}"
#   become: yes

# - name: Add my.cnf To Root Home
#   template:
#     src: templates/my.cnf.j2
#     dest: /root/.my.cnf
#     mode: 0600
#   become: yes

- name: Create MySQL Database
  mysql_db:
    name: '{{ mysql_database }}'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: Remove MySQL Anonymous User
  mysql_user:
    name: ''
    host: localhost
    state: absent  
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: 'Create MySQL User: {{ mysql_user }}'
  mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_user_password }}'
    host: '{{ app_server_address }}'
    priv: '{{ mysql_database }}.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  become: yes

- name: Setting up mysqld.cnf
  template:
    src: templates/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: 
    - Restart MySQL
  become: yes
