kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
data:
  PORT: {{ .Values.service.targetPort | quote }}
  JWT_EXPIRATION: '15m'
  VAULT_ADDR: {{ .Values.vaultServerAddress | quote }} 