apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{.Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- .Values.resources | toYaml | nindent 12}}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: {{ .Release.Name }}
