version: "3.6"
    
services:
  db:
    image: mariadb:10.8.2-rc-focal
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapi
      MYSQL_USER: myapi
      MYSQL_PASSWORD: awesomepass
    ports:
      - 3306:3306

  redis:
    image: redis:7.0-rc-alpine3.15
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    
volumes:
  db_data: {}
  redis_data: {}