version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - pgsql_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "mauri@local.dev"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8080:80

volumes:
  pgsql_data: {}