apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lockeyapi-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@bitbucket.org:mauricarmo/kubernetes.git'
    path: lockeyapi
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true