- name: Allow established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow established and related connections
  become: yes

- name: Allow Connections to Loopback Interface
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: Allow loopback connections
  become: yes

- name: Allow SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    jump: ACCEPT
    comment: Allow SSH
  become: yes

- name: Allow Portainer HTTP Port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '9443'
    jump: ACCEPT
    comment: Allow Portainer HTTP port
  become: yes

- name: Allow HTTP Port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT
    comment: Allow HTTP port
  become: yes

- name: Allow HTTPS Port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT
    comment: Allow HTTPS port
  become: yes

- name: Set DROP Policy for INPUT
  iptables:
    chain: INPUT
    policy: DROP
  become: yes