version: '3.4'

services:
  profile:
    image: profile
    build:
      context: profile
      dockerfile: ./Dockerfile
    environment:
      USER_API_URL: http://user:3001
      NODE_ENV: production
    ports:
      - 3000:3000

  user:
    image: user
    build:
      context: user
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
