apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: lockeyapi-canary-demo
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-demo
        image: maurifc/sample-app:blue
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 30
      - pause: {duration: 40s}
      - setWeight: 30
      - pause: {duration: 20s}
      - setWeight: 30
      - pause: {duration: 20s}