- name: Allow HTTP Port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT
    comment: Allow HTTP Port
  become: yes
  notify:
    - Save IPTables Rules

- name: Allow HTTPS Port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT
    comment: Allow HTTPS Port
  become: yes
  notify:
    - Save IPTables Rules