apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: default
spec:
  selector:
    app: hello
  type: ClusterIP
  ports:
  - name: hello-svc
    protocol: TCP
    port: 80
    targetPort: 8080
