- name: Install PHP 7.4
  apt:
    name:
      - php7.4
      - php7.4-fpm
      - php7.4-mysql
    state: present
    install_recommends: no
  become: yes

- name: Creating index.php
  template:
    src: files/index.php.j2
    dest: '{{ app_root_folder }}/index.php'
    owner: www-data
    group: www-data
    mode: 0644
  become: yes